### ISSUE TITLE
Invitation Email fails due to null reference

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#154]
This error was logged for firebase function onInvitationCreate

```TypeError: Cannot read property 'email' of undefined
    at exports.onInvitationCreate.functions.database.ref.onCreate (/user_code/index.js:105:29)
    at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:35:20
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)```

**Comment by johnneed** [comment]
This is the cause of the failed invitation emails

**Comment by johnneed** [comment]
Fixed in functions
